## add packages to Description file
usethis::use_dev_package("gradethis")
usethis::use_package("epiDisplay")
usethis::use_package("rio")
usethis::use_package("fs")
usethis::use_package("NHANES")
#usethis::use_package("tidyverse")
usethis::use_package("DiagrammeR")
usethis::use_package("tufte")
usethis::use_package("r2symbols")
usethis::use_package("visdat")
usethis::use_package("ggplot2")
usethis::use_package("learnr")
usethis::use_package("skimr")
usethis::use_package("lattice")
usethis::use_package("skimr")
usethis::use_package("epitools")
usethis::use_package("arsenal")
usethis::use_package("finalfit")
usethis::use_package("car")
usethis::use_package("png")
usethis::use_package("vembedr")
usethis::use_package("knitr")
usethis::use_package("dplyr")
usethis::use_package("jtools")
usethis::use_package("ggstance")
usethis::use_package("broom.mixed")
usethis::use_package("readr")
usethis::use_package("eulerr")
usethis::use_package("kableExtra")
usethis::use_package("knitr")
usethis::use_package("AF")
usethis::use_package("PerformanceAnalytics")
usethis::use_package("arsenal")

devtools::build_win()


## install package from
